CREATE TABLE tblDiscount
(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	Ad VARCHAR(80) NOT NULL,
	Rate SMALLINT NOT NULL
)
GO
CREATE TABLE tblCategori
(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	Ad VARCHAR(80) UNIQUE NOT NULL,
	Aciklama VARCHAR(1000)
)
GO
CREATE TABLE tblBrand
(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	Ad VARCHAR(80) UNIQUE NOT NULL
)
GO
CREATE TABLE tblProduct
(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	Indirim SMALLINT,
	Fiyat DECIMAL(10,2) NOT NULL,
	UrunImage VARCHAR(500),
	Aciklama VARCHAR(1000),
	Ad VARCHAR(80) NOT NULL,
	CategoriID INT FOREIGN KEY REFERENCES tblCategori(ID) NOT NULL,
	BrandID INT FOREIGN KEY REFERENCES tblBrand(ID) NOT NULL
)
GO
CREATE TABLE tblShoppingCart
(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	ToplamUcret DECIMAL(10,2) NOT NULL,
	ToplamSayi INT,
	KargoUcret DECIMAL(10,2),
	DiscounttID INT FOREIGN KEY REFERENCES tblDiscount(ID) NOT NULL
)
GO
CREATE TABLE tblUser
(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	Ad VARCHAR(80) NOT NULL,
	Tel CHAR(10) UNIQUE NOT NULL CONSTRAINT chkUserTel CHECK (Tel LIKE '[0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9][0-9]'),-- Telefon numarasi '5054653515' gibi 10 basamakli sayilardan olusmali.
	Email VARCHAR(50) CONSTRAINT chkUserMail CHECK (Email LIKE '%@%.%'),
	Sifre VARCHAR(100) NOT NULL,
	ShoppingCartID INT FOREIGN KEY REFERENCES tblShoppingCart(ID) NOT NULL
)
GO
CREATE TABLE tblComment
(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	Ad VARCHAR (80) NOT NULL,
	Aciklama VARCHAR(1000),
	Score DECIMAL(2,1),
	Tarih DATETIME,
	ProductID INT FOREIGN KEY REFERENCES tblProduct(ID) NOT NULL,
	Userid INT FOREIGN KEY REFERENCES tblUser(ID) NOT NULL
)
GO
CREATE TABLE tblFeature
(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	Ad VARCHAR(80) NOT NULL,
	Aciklama VARCHAR(1000)
)
GO
CREATE TABLE tblRelationsipProductFeature
(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	FeatureID INT FOREIGN KEY REFERENCES tblFeature(ID) NOT NULL,
	ProductID INT FOREIGN KEY REFERENCES tblProduct(ID) NOT NULL
)
GO
CREATE TABLE tblRelationshipProductShoppingCart
(
	ID INT IDENTITY(1,1) PRIMARY KEY,
	Adet INT NOT NULL DEFAULT 1,
	EklemeTarih DATETIME NOT NULL DEFAULT GETDATE(),
	KaldirmaTarih DATETIME NOT NULL DEFAULT GETDATE(),
	ShoppingCartID INT FOREIGN KEY REFERENCES tblShoppingCart(ID) NOT NULL,
	ProductID INT FOREIGN KEY REFERENCES tblProduct(ID) NOT NULL
)